image: ruby:2.4.6-slim-stretch

before_script:
  - apt-get update -qq && apt-get install -y -qq gcc ruby-dev libxslt-dev libxml2-dev zlib1g-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install

e2e:firefox:
  stage: test
  services:
    - selenium/standalone-firefox
  script:
    - rake cleanup
    - rake test
  artifacts:
    paths:  
      - reports/
  
deploy_surge: 
  stage: deploy
  before_script: 
    - npm install --global surge
  script: 
    - surge reports/ ruby-cucumber-sample.surge.sh --token $SURGE_TOKEN    
  when: always    
