language: ruby
rvm: 2.6.3

dist: xenial
services:
  - xvfb

cache:
  - bundler
  - apt

sudo: required

before_script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq google-chrome-stable
  - bundle install

script: 
  - rake test

deploy:
  skip_cleanup: true
  provider: surge
  project: ./mochawesome-report/
  domain: cypress-demo.surge.sh